name: RePi Default Workflow

on: [push]

jobs:

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: FilipM13/RePi@main
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Format code with black formatter
        uses: FilipM13/RePi@main
        run: |
          pip install -r requirements_dev.txt
          black src

  code_quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install requirements
        uses: FilipM13/RePi@main
        run: pip install -r requirements_dev.txt

      - name: Check flake8 on source
        run: flake8 src

      - name: Check flake8 on tests
        run: flake8 tests

      - name: Check mypy on source
        run: mypy src

  test_37:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Get requirements
        uses: FilipM13/RePi@main
        run:
          pip install .
          pip install -r requirements.txt

      - name: Pytest functionalities
        run:
          pytest tests

  test_39:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Get requirements
        uses: FilipM13/RePi@main
        run:
          pip install .
          pip install -r requirements.txt

      - name: Pytest functionalities
        run:
          pytest tests