name: Octo Organization CI

on:
  - push

jobs:
  format:
    runs-on:
      os: ubuntu-latest
      python: 3.7

    steps:
      - name: Format code with black formatter
        run:
          pip install -r requirements_dev.txt
          flake8 src

  code_quality:
    runs-on:
      os: ubuntu-latest
      python: 3.7

    steps:
      - name: Quality checks on source code and test
        run:
          pip install -r requirements_dev.txt
          flake8 src
          flake8 tests
          mypy src

  test_37:
    runs-on:
      os: ubuntu-latest
      python: 3.7

    steps:
      - name: Pytest functionalities
        run:
          pip install .
          pip install -r requirements.txt
          pytest tests

  test_39:
    runs-on:
      os: ubuntu-latest
      python: 3.9

    steps:
      - name: Pytest functionalities
        run:
          pip install .
          pip install -r requirements.txt
          pytest tests